# Generated by Django 5.1.4 on 2025-01-10 02:33

import customer_app.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, validators=[customer_app.validators.validate_name])),
                ('last_name', models.CharField(max_length=100, validators=[customer_app.validators.validate_name])),
                ('email', models.CharField(default=None, max_length=200, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('phone_number', models.CharField(max_length=30)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
