# Generated by Django 5.1.4 on 2025-03-14 00:39

import customer_app.validators
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, validators=[customer_app.validators.validate_name])),
                ('last_name', models.CharField(max_length=100, validators=[customer_app.validators.validate_name])),
                ('email', models.CharField(default=None, max_length=200, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('phone_number', models.CharField(max_length=30)),
                ('message_hour', models.IntegerField(blank=True, default=9, validators=[django.core.validators.MaxValueValidator(24), django.core.validators.MinValueValidator(0)])),
                ('timezone', models.CharField(blank=True, max_length=63, null=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
