services:
  api:
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
      - celery
      - celery-beat

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=customer_db
    ports:
      - '5454:5432'
    volumes: 
      - postgres_data:/var/lib/postgresql/data
  
  redis:
    image: redis:alpine
    ports:
      - '6379:6379'

  celery:
    build: .
    command: ./wait-for-it.sh redis:6379 -- celery -A encouragement_proj worker --loglevel=info
    volumes:
      - .:/src
    depends_on:
      - redis
      - db

  celery-beat:
    build: .
    command: ./wait-for-it.sh redis:6379 -- celery -A encouragement_proj beat --loglevel=info
    volumes:
      - .:/src
    depends_on:
      - redis
      - db

volumes:
  postgres_data: